INFO:root:Navigated to polybuzz login page
INFO:root:User has confirmed login
INFO:root:Navigating back to the main polybuzz page
INFO:root:Begin selecting the character: Character_1
INFO:root:Refreshed the page.
INFO:root:Clicked on the chatbot button.
ERROR:root:Error occurred while selecting the character: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

ERROR:root:Error occurred during conversation generation: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

INFO:root:Page refreshed successfully
INFO:root:Begin selecting the character: Character_1
INFO:root:Refreshed the page.
INFO:root:Clicked on the chatbot button.
ERROR:root:Error occurred while selecting the character: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

ERROR:root:Error occurred during conversation generation: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

INFO:root:Page refreshed successfully
INFO:root:Begin selecting the character: Character_1
INFO:root:Refreshed the page.
INFO:root:Clicked on the chatbot button.
ERROR:root:Error occurred while selecting the character: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

ERROR:root:Error occurred during conversation generation: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

INFO:root:Page refreshed successfully
INFO:root:Begin selecting the character: Character_1
INFO:root:Refreshed the page.
INFO:root:Clicked on the chatbot button.
ERROR:root:Error occurred while selecting the character: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

ERROR:root:Error occurred during conversation generation: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

INFO:root:Page refreshed successfully
INFO:root:Begin selecting the character: Character_1
INFO:root:Refreshed the page.
INFO:root:Clicked on the chatbot button.
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10429ad50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2e3dab36-391f-40b0-adf0-5b3faa939cc4
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104310250>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2e3dab36-391f-40b0-adf0-5b3faa939cc4
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104310f10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2e3dab36-391f-40b0-adf0-5b3faa939cc4
